### PR TITLE
Update recruiters.yml

### PR DESCRIPTION
**Pull request by kirtisagar**
Removed aditi.com because it is reputed company check out www.aditi.com

### CODE REVIEW

**Comment by kazanart** [comment]
This is defamation.  Capital Markets Placement is an honest company that helps thousands of people get jobs.  By placing these companies on this list you are hurting honest people working in them and preventing thousands of people from getting better jobs and companies from finding good people.  This is a pretty horrible thing to do.

Remove capitalmarketsp.com from your list immediately.

**Comment by soffes** [comment]
Fixed in efead6b265b13e2abf5fd0da25b0bebc2f801272

**Comment by nathansmith** [comment]
@kazanart "Defamation," lulz.

@soffes Well, you tried Sam. Thanks for the endeavor, while it lasted.

**Comment by soffes** [comment]
@nathansmith thanks for all of your help with this over the years! <3

**Pull request closed without merging**
